Sikkim_Workshop/amit-kumar.txt

amit kumar

---

Sikkim_Workshop/Akshay.txt

i have added my email
b160106@nitsikkim.ac.in

Added a file named Akshay.txt

---

Sikkim_Workshop/anshu.txt

i have added my name and email id

added my name and email id

---

Sikkim_Workshop/reshab_gupta.txt

my name is reshab gupta

---

Sikkim_Workshop/Praashant.txt

i have added my email address and user name.

email address and name added

---

Sikkim_Workshop/shobham.txt

i have added my name and my email id in a txt dile

added my name and email

---

Sikkim_Workshop/nishu.txt

i have added my name and my email in txt file

Added my name to sikkim workshop folder

---

Sikkim_Workshop/ashwani.txt

this file is updated by ashwani

---

Sikkim_Workshop/divyanshi.txt

file containing my name was added

---

Sikkim_Workshop/SAMEER_Choubey.txt

Please add this .txt file
#Part of Workshop

Added my name to the Sikkim Workshop folder.

---

Sikkim_Workshop/Avnish1234.txt

added a file Avnish1234.txt to Sikkim_Workshop

---

Sikkim_Workshop/Nitin-Choudhary.txt

I have added my email -id along with my name in a new txt file.

Added a file named my-name.txt to Sikkim_Workshop folder

---

Sikkim_Workshop/GauravKumar.txt

add Gaurav's name

---

Sikkim_Workshop/Aquil-Hussain.txt

add Aquil Hussain name

---

Sikkim_Workshop/Tshiteej.txt

Tshiteej add name and roll

---

ANeeL.txt

Add ANeeL Name 

---

Sikkim_Workshop/meraj.txt

Add meraj name

---

Sikkim_Workshop/sumitbothra.txt

added sumit bothra

---

Sikkim_Workshop/manish.txt
manish.txt

succesfully added

---

Sikkim_Workshop/rupesh.txt

Add Rupesh

---

Sikkim_Workshop/ravi.txt

info added fpr Ravi

---

Sikkim_Workshop/Abisek-Dahal.txt

hacker  Nikki (abisek dahal)

---

Sikkim_Workshop/trishugupta.txt

add  trishu name

---

Sikkim_Workshop/bgc.txt

iron-maiden-666

---

Sikkim_Workshop/sangam.txt

Added Sangam's file

---

Sikkim_Workshop/prativa.txt

i had changed  something that is more important 
somthing cool 
prativa bandana anish are fool
ya hooo

added prativa.txt

---

Sikkim_Workshop/salu.txt

my first page

---

kismat.txt

Added kismat.txt

---

ANeeL.txt
manish.txt

Removed 2 .txt file from outside of workshop folder

---

Sikkim_Workshop/shyam.txt

hi this is shyam

---

Sikkim_Workshop/Avnish1234.txt

hello i am adding another  branch feature3

succesfully added feature3.

---

Sikkim_Workshop/SAMEER_Choubey.txt
Sikkim_Workshop/Sameer.txt

Changing few file, major files

---

workshopkgp/vaibhav_16CS10051.txt

add my file

---

workshopkgp/thealphadollar.txt

Please accept this pull request and merge the file with whatever you have.

Shivam Kumar Jha 17CS30033

---

workshopkgp/bhupsh.txt

add this one 

---

workshopkgp/16CE10024.txt
workshopkgp/rohit_reddy.txt
workshopkgp/sampreeth.txt

Added mine and my friends names and emails

add sampreeth1999.txt

---

workshopkgp/uttam.txt

add uttam.txt

---

workshopkgp/abhishek.txt

add abhishek.txt

---

workshopkgp/divyansh_17ma20014.txt

divyansh_17ma20014.txt

---

workshopkgp/parakh.txt

added my name and email in a file... accept it.

add parakh.txt

---

workshopkgp/akshaydeuri.txt

Pull request to add akshay.txt

add akshay.txt

---

workshopkgp/yash.txt

add yash.txt

---

workshopkgp/sahil.txt

The name and email id was added

add sahil.txt

---

workshopkgp/vaibhav.txt

add vaibhav.txt

---

workshopkgp/gurjot.txt

add gurjot.txt

---

workshopkgp/prakhar.txt

name and email

---

workshopkgp/amit_27.txt

add amit_27.txt

---

workshopkgp/vedant_saraswat.txt

added vedant.txt

---

workshopkgp/newFileEE.txt

 Added Files

---

workshopkgp/manu.txt

first commit

---

workshopkgp/saketh.txt

added my name and email in a file

add saketh.txt

---

workshopkgp/nandikeshsingh.txt
workshopkgp/nitin.txt

added the required file

---

workshopkgp/ravitejabhukya.txt

add ravitejabhukya

---

workshopkgp/jalaj_17MA20020.txt

added my name and email in a file

add jalaj_17MA20020.txt

---

workshopkgp/vishwajeet.txt

added vishwajeet.txt

---

workshopkgp/ngs.txt

adding my name and emailid into sandbox

add ngs.txt

---

workshopkgp/meher.txt

add meher.txt

---

workshopkgp/kabeer.txt

kabeer.txt added

---

workshopkgp/rishabhdeepsingh.txt

Added my name and e-mail in a file.

add Rishabh Deep Singh

---

workshopkgp/bourne.txt

Added my name  and email in it.

what is happening

---

workshopkgp/vineeth.txt

added vineeth.txt

---

workshopkgp/16EE10046.txt

Added my name and email in a file.

add 16EE10046.txt

---

workshopkgp/silla.txt

ädd silla.txt

---

workshopkgp/ankit_16MI33004.txt

ADDED USERNAME AND ID

---

workshopkgp/anubhav_16MA20011.txt

Name and Email ID added in a file.

Name and Email ID added

---

workshopkgp/shrey17.txt

kindly accept this pull request

add shrey17.txt

---

workshopkgp/aravind.txt

Finally up for it....
just added my details

add aravind.txt

---

workshopkgp/anjali.txt

Anjali.txt added which contains my name and email-id details

anjali.txt added

---

workshopkgp/rajesh.txt

Add my name and email in a file

sdd rajesh.txt

---

workshopkgp/vivek_17cs10002.txt

add vivek_17cs10002.txt

---

workshopkgp/pavan_16IM30004.txt

add file named pavan_roll no

---

workshopkgp/manoj.txt

add manoj.txt

---

workshopkgp/AaradhyaSawant.txt

Added AaradhyaSawant.txt

---

workshopkgp/file.txt

think as a final commit

---

workshopkgp/ravi.txt

add ravi.txt

---

workshopkgp/sd.txt

adding sd.txt

---

workshopkgp/dibya.txt

add dibya.txt

---

workshopkgp/vishal.txt

Added my name and email in file

Vishal.txt added

---

workshopkgp/nitish.txt

nitish.txt

---

workshopkgp/saif.txt

Added my name and email address.

add saif.txt

---

workshopkgp/arib.txt

Added my name and email in the file

add arib.txt

---

workshopkgp/Pratik.txt

add Pratik.txt

---

workshopkgp/gaurav.txt

add gaurav.txt

---

workshopkgp/akash.txt

add akash.txt

---

workshopkgp/satyamkgpiit.txt

includes my name depaentment and email.

add satyamkgpiit.txt

---

workshopkgp/mayank_agrawal.txt

add mayank_agrawal.txt

---

workshopkgp/dewang.txt

add dewang.txt

---

workshopkgp/rk.txt

add file temo

---

shivam.txt

Shivam kumar jha

---

workshopkgp/darpan.txt

added darpan.txt

---

workshopkgp/ritik_250.txt

add ritk_250.txt

---

workshopkgp/ashuak37.txt

Added my name and email in a file created in workshop folder.

add ashuak37.txt

---

workshopkgp/yash_17MA20050.txt

Name and Email added

---

workshopkgp/piyush.txt

added my name and email id in a file.

Added piyush.txt

---

internal_session/v.txt

add internal_session

---

internal_session/anushka.txt

Add a new file anushka.txt

---

internal_session/README.md

Add nikhil in README

---

internal_session/README.md

added name roll number
